# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.boot_timeout = 100000

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.synced_folder "/Users/christiankroer/Documents/research/optimization/robust_cpp/", "/home/vagrant/robust/"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install build-essential
      apt-get install cmake
      apt-get install autotools
      apt-get install autotools-dev autoconf
      apt-get install unzip
      # set up Eigen
      wget http://bitbucket.org/eigen/eigen/get/3.3.3.tar.gz
      tar xvf 3.3.3.tar.gz
      cd eigen-eigen*
      mkdir build
      cd build/
      cmake ..
      make install
      export EIGEN_HOME=/usr/local/
      # set up spdlog
      cd
      wget https://github.com/gabime/spdlog/archive/v0.13.0.zip
      unzip v0.13.0.zip
      cd spdlog*
      cd include/
      cp -r spdlog /usr/local/include/
      # set up gurobi
      cd
      wget http://packages.gurobi.com/7.0/gurobi7.0.2_linux64.tar.gz
      tar xvf gurobi7.0.2_linux64.tar.gz
      cd gurobi702/linux64/
      cp bin/* /usr/local/bin/
      cp include/* /usr/local/include/
      cp lib/* /usr/local/lib/
      export GRB_LICENSE_FILE=/home/vagrant
      export GUROBI_HOME=/usr/local/
      cd
      wget https://cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.sh
      # figure out how to handle prompt
      # sh cmake-3.8.2-Linux-x86_64.sh --prefix=/usr/local/
  SHELL
end
